version: '3.7'
services:
    # Run the caddy server        
    caddy:
        #tty: true
        build: .
        container_name: caddy
        #restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
